import 'dart:math';

/// The NDID **Common Message** standard, as an RP must show it.
///
/// Source: *005 แนวทางการพัฒนาบริการ NDID สำหรับสมาชิก* Rev. 1.0 (11 Feb 2021),
/// §6.2.1 "มาตรฐาน Common Message สำหรับบทบาทผู้ให้บริการ (Relying Party: RP)",
/// pages 31–39. Added 2026-08-28 after NDID rejected the app review — issue 3
/// asked for exactly these strings.
///
/// The wording here is **quoted from that document**; `test/
/// ndid_common_message_test.dart` checks every message still appears verbatim in
/// the PDF's own text, so a well-meant reword cannot silently drift off the
/// standard. Three rules from the same section shape the API:
///
/// * §6.2.1 bullet 4 — where the document writes `[RP]` or `[IdP]`, the member
///   must substitute the **marketing name**, not the literal word. Hence
///   [rpMarketingName] and the `idpName` arguments.
/// * §6.2.1 bullet 2 — a member may adjust wording for clarity, provided the
///   customer knows what happened and what to do next. That is the licence
///   under which [requestMessage] drops the document's AS clause; see there.
/// * Page 38 note — the Transaction Ref is generated by the RP, is **digits
///   only**, and is 5–9 digits long. See [NdidTransactionRef].
abstract final class NdidCommonMessage {
  /// The RP Marketing Name shown to customers, per §6.2.1 bullet 4.
  static const String rpMarketingName = 'บริษัท ศรีสวัสดิ์ พาวเวอร์ 2014 จำกัด';

  /// Contact shown by the AS-error messages, which the standard writes as
  /// "RP Contact XXX".
  ///
  /// **Deliberately empty by default.** Four AS messages tell the customer to
  /// contact us, and a wrong phone number in front of a customer is worse than
  /// none — so rather than invent one, an unset value falls back to
  /// "ติดต่อผู้ให้บริการ". Set it with
  /// `--dart-define=NDID_RP_CONTACT=ศูนย์บริการลูกค้า 1652` once the real
  /// number is confirmed.
  static const String rpContact =
      String.fromEnvironment('NDID_RP_CONTACT', defaultValue: '');

  /// `ติดต่อ <contact>` — or the generic form when no contact is configured.
  static String get _contactClause =>
      rpContact.isEmpty ? 'ติดต่อผู้ให้บริการ' : 'ติดต่อ $rpContact';

  /// §6.2.1 [2] — shown before the customer picks an IdP.
  static const String chooseIdp =
      'กรุณาเลือกผู้ให้บริการยืนยันตัวตน ที่ท่านเคยลงทะเบียนไว้เพื่อยืนยันตัวตน'
      'และมีโมบายแอปพลิเคชันของผู้ให้บริการยืนยันตัวตนดังกล่าว';

  /// §6.2.1 [3] — shown after the customer picks an IdP, while the request is
  /// waiting. The 60 minutes is the standard RP request timeout, which is what
  /// `NdidApi.createVerifyRequest` asks for.
  static const String waitingForIdp =
      'กรุณาไปยืนยันตัวตนที่โมบายแอปพลิเคชันของผู้ให้บริการที่ท่านเลือก '
      'ภายใน 60 นาที และกลับมาทำรายการต่อที่นี่';

  /// §6.2.1 [5] — the customer cancelled the request or switched IdP.
  ///
  /// ⚠ One word differs from the document, which ends "กรุณาเลือก **IdP**
  /// รายอื่น". Bullet 4 of the same section says not to show the customer the
  /// literal word "IdP", and every other message in the table spells it
  /// "ผู้ให้บริการยืนยันตัวตนรายอื่น" — so the standard contradicts itself here
  /// and this follows the rule rather than the typo.
  static const String cancelledOrChangedIdp =
      'ท่านได้ยกเลิกรายการคำขอหรือเปลี่ยนผู้ให้บริการยืนยันตัวตน '
      'กรุณาเลือกผู้ให้บริการยืนยันตัวตนรายอื่น';

  /// Page 39 — the catch-all the standard gives for RP API V4, used for any
  /// failure with no more specific message (an unknown error code included).
  static const String generalFailure =
      'ท่านไม่สามารถทำรายการได้ในขณะนี้ '
      'กรุณาทำรายการใหม่หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น';

  /// The Request Message sent to the IdP and shown in the IdP's own app
  /// (§6.2.1 [28], page 37).
  ///
  /// The document's template is:
  ///
  /// > "ท่านกำลังยืนยันตัวตนเพื่อใช้ตามวัตถุประสงค์ของ \[RP\] และประสงค์ให้ส่ง
  /// > ข้อมูลจาก \[AS 1, AS 2, …\] (Transaction Ref:12345678)"
  ///
  /// ⚠ **The AS clause is deliberately dropped.** This flow calls
  /// `POST /rp/verify` in mode 2 with no `data_request_list` — there is no
  /// Authoritative Source in the request, so naming one would tell the customer
  /// their data is being fetched from a bank when it is not. §6.2.1 bullet 2
  /// permits adjusting the wording as long as the customer understands what is
  /// happening, and omitting a party we do not call is the honest reading.
  /// If a data request is ever added, put the AS names back.
  ///
  /// ⚠ **[transactionRef] is normally omitted now** (2026-08-31). The srisawad
  /// NDID gateway generates the Transaction Ref itself and appends the
  /// `(Transaction Ref: …)` clause to this message server-side, then returns the
  /// value on `POST /rp/verify` and every `GET /rp/verify/{ref}` so the waiting
  /// screen can quote it. Passing one here would put a *second*, different
  /// reference in front of the customer — which is the state NDID rejected the
  /// review over, wearing the opposite mistake. Pass one only for a gateway that
  /// does not compose the clause itself (the DAP/SIT node).
  static String requestMessage({String? transactionRef}) {
    const base =
        'ท่านกำลังยืนยันตัวตนเพื่อใช้ตามวัตถุประสงค์ของ$rpMarketingName';
    return transactionRef == null || transactionRef.isEmpty
        ? base
        : '$base (Transaction Ref: $transactionRef)';
  }

  /// The standard message for an IdP or AS error code (§6.2.1 [10]–[27]).
  ///
  /// [idpName] is the IdP Marketing Name, substituted where the document writes
  /// `[IdP]`. An unknown or absent code gives [generalFailure] rather than
  /// showing the customer a raw number.
  static String forErrorCode(int? code, {String idpName = ''}) {
    final idp = idpName.trim().isEmpty
        ? 'ผู้ให้บริการยืนยันตัวตนที่ท่านเลือก'
        : idpName.trim();
    return switch (code) {
      // ── IdP error codes ──────────────────────────────────────────
      30000 => 'ผู้ให้บริการยืนยันตัวตนที่ท่านเลือกไม่สามารถให้บริการได้ในขณะนี้ '
          'กรุณาทำรายการใหม่หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30200 => 'ไม่สามารถทำรายการได้ในขณะนี้ '
          'กรุณาตรวจสอบเลขบัตรประชาชนของท่านและทำรายการใหม่ '
          'หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30300 => 'ไม่พบข้อมูลของท่านในฐานข้อมูลผู้ใช้บริการของผู้ให้บริการยืนยัน'
          'ตัวตนที่ท่านเลือก กรุณาเลือกผู้ให้บริการยืนยันตัวตนรายอื่นที่ท่าน'
          'เคยลงทะเบียนและมีโมบายแอปพลิเคชัน',
      30400 => 'ขออภัย ข้อมูลของท่านไม่เป็นปัจจุบัน กรุณาติดต่อผู้ให้บริการ'
          'ยืนยันตัวตนที่ท่านเลือกเพื่ออัปเดทข้อมูล หรือเลือกผู้ให้บริการยืนยัน'
          'ตัวตนรายอื่น',
      30500 => 'การยืนยันตัวตนไม่สำเร็จเนื่องจากท่านระบุ PIN ผิด, ภาพถ่ายไม่'
          'ชัดเจน กรุณาทำรายการใหม่ หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30510 => 'การยืนยันตัวตนไม่สำเร็จเนื่องจากท่านระบุ PIN/Password ไม่'
          'ถูกต้อง กรุณาทำรายการใหม่ หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30520 => 'การยืนยันตัวตนไม่สำเร็จเนื่องจากท่านยืนยันตัวตนด้วยระบบจดจำ'
          'ใบหน้า (Face Recognition) ไม่ผ่านตามเงื่อนไขที่กำหนด กรุณาทำ'
          'รายการใหม่ หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30530 => 'การยืนยันตัวตนไม่สำเร็จเนื่องจากท่านระบุรหัส OTP ไม่ถูกต้อง '
          'กรุณาทำรายการใหม่ หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30600 => 'การยืนยันตัวตนไม่สำเร็จ เนื่องจากท่านได้ยกเลิกรายการยืนยัน'
          'ตัวตนที่โมบายแอปพลิเคชันของผู้ให้บริการยืนยันตัวตน กรุณาเลือก'
          'ผู้ให้บริการยืนยันตัวตนรายอื่น',
      30610 => 'การยืนยันตัวตนไม่สำเร็จ เนื่องจากท่านไม่ได้ยอมรับเงื่อนไขการ'
          'ให้บริการยืนยันตัวตนของผู้ให้บริการยืนยันตัวตนที่ท่านเลือก กรุณา'
          'ทำรายการใหม่ หรือเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30700 => 'การยืนยันตัวตนไม่สำเร็จ เนื่องจากผู้ให้บริการยืนยันตัวตนที่ท่าน'
          'เลือกไม่สามารถให้บริการได้ในขณะนี้ กรุณาทำรายการใหม่ หรือ'
          'เลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      30800 => 'ท่านยังไม่ได้ลงทะเบียนและยอมรับเงื่อนไขการใช้บริการ NDID ที่โม'
          'บายแอปพลิเคชันของผู้ให้บริการยืนยันตัวตน กรุณาดำเนินการก่อน'
          'ทำรายการ',
      // The one message that names the IdP, per §6.2.1 bullet 4.
      30900 => 'ไม่สามารถทำรายการได้ในขณะนี้ เนื่องจากอยู่นอกเวลาการ'
          'ให้บริการของ $idp กรุณาเลือกผู้ให้บริการยืนยันตัวตนรายอื่น',
      // ── AS error codes ───────────────────────────────────────────
      40000 => 'ขออภัย ท่านไม่สามารถทำรายการได้ในขณะนี้ กรุณาทำรายการ'
          'ใหม่ หรือ$_contactClause',
      40200 => 'ขออภัย ไม่สามารถดำเนินการต่อได้เนื่องจากท่านใส่เลขบัตร'
          'ประชาชนไม่ถูกต้อง กรุณาทำรายการใหม่อีกครั้ง',
      40300 => 'ขออภัย ไม่สามารถดำเนินการต่อได้ กรุณา$_contactClause',
      40400 => 'ขออภัย ไม่สามารถดำเนินการต่อได้เนื่องจากข้อมูลไม่ถูกต้อง กรุณา'
          'ทำรายการใหม่อีกครั้ง หรือ$_contactClause',
      40500 => 'ขออภัย ไม่สามารถดำเนินการต่อได้ กรุณา$_contactClause',
      _ => generalFailure,
    };
  }

  /// The message for a finished-but-unsuccessful request status.
  ///
  /// [errorCode] wins when the IdP or AS gave one, since the standard's table is
  /// keyed on it; otherwise the status itself decides. `CANCELLED` maps to
  /// §6.2.1 [5], and everything else falls back to the general failure rather
  /// than inventing wording the standard does not have.
  static String forStatus(String status, {int? errorCode, String idpName = ''}) {
    if (errorCode != null) {
      return forErrorCode(errorCode, idpName: idpName);
    }
    return switch (status.toUpperCase()) {
      'CANCELLED' => cancelledOrChangedIdp,
      // NDID counts a timeout as the customer not acting in time; the standard
      // has no dedicated string, so the general one carries the retry advice.
      'TIMEOUT' => generalFailure,
      _ => generalFailure,
    };
  }
}

/// The customer-facing **Transaction Ref**.
///
/// Page 38 of the NDID guideline: *"Transaction Ref. (หมายเลขอ้างอิง) : RP
/// ทำการ generate เอง และแสดงหมายเลข Transaction Ref. โดยต้องมีความยาวขั้นต่ำ 5
/// ตัว แต่ไม่เกิน 9 ตัว และเป็นเฉพาะตัวเลขเท่านั้น"* — the RP generates it
/// itself, digits only, 5 to 9 of them.
///
/// This exists because **NDID's `reference_id` cannot serve as one**: it is a
/// UUID minted by the NDID proxy, and the screen used to show its first 12
/// characters upper-cased (`8CB4B22F15A4`), which is neither numeric nor ≤ 9
/// long. That was issue 2 of the 2026-08-28 review rejection.
///
/// The same value must appear in two places — on our waiting screen and inside
/// the Request Message the IdP app displays — so one party has to own it.
///
/// **Since 2026-08-31 that party is the gateway, not this app.** The srisawad
/// NDID backend generates the reference, appends it to the Request Message it
/// forwards to the IdP, and returns it as `transaction_ref` on `POST /rp/verify`
/// and on every `GET /rp/verify/{reference_id}`. The waiting screen displays
/// what comes back. That is strictly better than generating it here: with one
/// generator there is no way for the screen and the IdP app to disagree, which
/// is the failure NDID actually rejected.
///
/// So [isValid] is now the load-bearing member — it checks the *gateway's*
/// value against the standard's rule, and `ndid_verify_page` leaves a
/// breadcrumb when it fails. [generate] is kept as the RP-side fallback for a
/// gateway that composes no clause of its own (the DAP/SIT node); nothing in
/// the live flow calls it.
abstract final class NdidTransactionRef {
  /// Longest the standard allows, and what this app uses.
  static const int digits = 9;

  static final Random _random = Random();

  /// A fresh reference: exactly [digits] digits, zero-padded.
  ///
  /// ⚠ **Not used by the live flow** — the gateway supplies `transaction_ref`.
  /// This is the fallback for a gateway that doesn't, and it must be paired with
  /// `NdidCommonMessage.requestMessage(transactionRef: …)` so the IdP quotes the
  /// same number; using it alone shows the customer a reference their bank
  /// never saw.
  ///
  /// Leading zeros are fine — the standard's own example is `000000001` — so
  /// this pads rather than forcing a first digit of 1-9, which would quietly
  /// shrink the range.
  static String generate() =>
      _random.nextInt(1000000000).toString().padLeft(digits, '0');

  /// Whether [ref] satisfies the standard: 5–9 characters, digits only.
  static bool isValid(String ref) =>
      RegExp(r'^[0-9]{5,9}$').hasMatch(ref);
}
